Code Review for the Design & UX
euqueme/heat-map pull request #1
Opened 2019-09-05 22:20 UTC by majovainilla

**This is the first code review request to evaluate our page.**

Considerations:

The HTML validation got an error when using` |` to add multiple fonts on the HTML file. 
Should we change it and add multiple links or should we leave it like that?

2019-09-05 22:26 UTC, stratospherique reviewed
### Pull request under the review by Ahmed Mahfoudh TSE

2019-09-05 22:37 UTC, stratospherique requested changes
### Great work team :clap: :clap: . However, some requirements that prevents your project's approval needs to be implemented. check below :arrow_down: 

#### Page structure

##### Footer

* [x] It contains centered links (content is not important).

#### Implementation details

##### Each article

* [x] It uses [`article` tag](https://www.w3schools.com/tags/tag_article.asp).
> wrap your article divs inside an `article` tag

### That's it :relaxed: . Keep up the good work :muscle: . When finsihed, kindly resubmit another code review request :pray: .

2019-09-06 16:18 UTC, majovainilla commented
Changed the requirements.

Considerations:

1. The HTML validation shows a warning due to the use of the article tag that has no <h1> because we used it to wrap all the article tags inside it.

2. The HTML validation got the previously mentioned error when using `|` to add multiple fonts on the HTML file.

2019-09-06 18:54 UTC, samgaco approved these changes
#### Hi @majovainilla and @euqueme 

### The project looks great :100: it is approved :1st_place_medal: 

-------------

#### Please address this before merging to the master branch :red_circle: 

* You could encode those `|`elements in the URL for the fonts using the [encoding](https://grox.net/utils/encoding.html) for this character , which would be `%7`.

--------------

#### By the way, well done on documenting the pull request :+1: :clap: hope you keep this up, just another petition :arrow_down: 

* **[For your next code review requests]**  Use meaningful names for your Pull Requests

-------------

* _Summary: Please, correct the error with the `|` character. Once that is done, your project is already approved so you can merge to the master branch and submit the project completion form right away. You could take some time to improve the appearance of the readme file but that is optional._ 

* ###### STATUS OF THE PROJECT: APPROVED :heavy_check_mark:

2019-09-06 18:54 UTC, samgaco commented on README.md
> +@majovainilla
Nicely documented readme file :+1: 

Some links to improve the appearance of your readme files. A free course [here](https://www.udacity.com/course/writing-readmes--ud777) and some template for inspiration [here](https://github.com/othneildrew/Best-README-Template).

2019-09-06 21:30 UTC, merged